# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5958dacd9f2fb5f2be7e576ddbcdfd958e4f86e9bdc36a8ada17a968e119cc94edc4ff391bbeff6f41f1c1932bfa05389ccfc93cf3fbab3b736122c500de16f9

test:
  secret_key_base: fddee9fad299ca15eea61c05a27582490a111598dfa22a164119170a2c55807a31d1c2cf3ee70a6995d5738f6bf112dd566b9a33b7d3c96123346d2c64e90f95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
